//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEnvios.ServiceLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/ServicioMVCEnvios.Models")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLogin.IServicioLogin")]
    public interface IServicioLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/Login", ReplyAction="http://tempuri.org/IServicioLogin/LoginResponse")]
        MVCEnvios.ServiceLogin.Login Login(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/Login", ReplyAction="http://tempuri.org/IServicioLogin/LoginResponse")]
        System.Threading.Tasks.Task<MVCEnvios.ServiceLogin.Login> LoginAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/AgregarLogin", ReplyAction="http://tempuri.org/IServicioLogin/AgregarLoginResponse")]
        void AgregarLogin(MVCEnvios.ServiceLogin.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/AgregarLogin", ReplyAction="http://tempuri.org/IServicioLogin/AgregarLoginResponse")]
        System.Threading.Tasks.Task AgregarLoginAsync(MVCEnvios.ServiceLogin.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/ListarLogins", ReplyAction="http://tempuri.org/IServicioLogin/ListarLoginsResponse")]
        MVCEnvios.ServiceLogin.Login[] ListarLogins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/ListarLogins", ReplyAction="http://tempuri.org/IServicioLogin/ListarLoginsResponse")]
        System.Threading.Tasks.Task<MVCEnvios.ServiceLogin.Login[]> ListarLoginsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/EliminarLogins", ReplyAction="http://tempuri.org/IServicioLogin/EliminarLoginsResponse")]
        void EliminarLogins(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/EliminarLogins", ReplyAction="http://tempuri.org/IServicioLogin/EliminarLoginsResponse")]
        System.Threading.Tasks.Task EliminarLoginsAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/EditarLogins", ReplyAction="http://tempuri.org/IServicioLogin/EditarLoginsResponse")]
        void EditarLogins(MVCEnvios.ServiceLogin.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/EditarLogins", ReplyAction="http://tempuri.org/IServicioLogin/EditarLoginsResponse")]
        System.Threading.Tasks.Task EditarLoginsAsync(MVCEnvios.ServiceLogin.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/BuscarLogin", ReplyAction="http://tempuri.org/IServicioLogin/BuscarLoginResponse")]
        MVCEnvios.ServiceLogin.Login BuscarLogin(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/BuscarLogin", ReplyAction="http://tempuri.org/IServicioLogin/BuscarLoginResponse")]
        System.Threading.Tasks.Task<MVCEnvios.ServiceLogin.Login> BuscarLoginAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLoginChannel : MVCEnvios.ServiceLogin.IServicioLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLoginClient : System.ServiceModel.ClientBase<MVCEnvios.ServiceLogin.IServicioLogin>, MVCEnvios.ServiceLogin.IServicioLogin {
        
        public ServicioLoginClient() {
        }
        
        public ServicioLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCEnvios.ServiceLogin.Login Login(string usuario, string password) {
            return base.Channel.Login(usuario, password);
        }
        
        public System.Threading.Tasks.Task<MVCEnvios.ServiceLogin.Login> LoginAsync(string usuario, string password) {
            return base.Channel.LoginAsync(usuario, password);
        }
        
        public void AgregarLogin(MVCEnvios.ServiceLogin.Login login) {
            base.Channel.AgregarLogin(login);
        }
        
        public System.Threading.Tasks.Task AgregarLoginAsync(MVCEnvios.ServiceLogin.Login login) {
            return base.Channel.AgregarLoginAsync(login);
        }
        
        public MVCEnvios.ServiceLogin.Login[] ListarLogins() {
            return base.Channel.ListarLogins();
        }
        
        public System.Threading.Tasks.Task<MVCEnvios.ServiceLogin.Login[]> ListarLoginsAsync() {
            return base.Channel.ListarLoginsAsync();
        }
        
        public void EliminarLogins(long id) {
            base.Channel.EliminarLogins(id);
        }
        
        public System.Threading.Tasks.Task EliminarLoginsAsync(long id) {
            return base.Channel.EliminarLoginsAsync(id);
        }
        
        public void EditarLogins(MVCEnvios.ServiceLogin.Login login) {
            base.Channel.EditarLogins(login);
        }
        
        public System.Threading.Tasks.Task EditarLoginsAsync(MVCEnvios.ServiceLogin.Login login) {
            return base.Channel.EditarLoginsAsync(login);
        }
        
        public MVCEnvios.ServiceLogin.Login BuscarLogin(long id) {
            return base.Channel.BuscarLogin(id);
        }
        
        public System.Threading.Tasks.Task<MVCEnvios.ServiceLogin.Login> BuscarLoginAsync(long id) {
            return base.Channel.BuscarLoginAsync(id);
        }
    }
}
