//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEnvios.ServiceEstadoPaquete {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPaquete", Namespace="http://schemas.datacontract.org/2004/07/ServicioMVCEnvios.Models")]
    [System.SerializableAttribute()]
    public partial class EstadoPaquete : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Trazabilidad[] TrazabilidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Trazabilidad[] Trazabilidad {
            get {
                return this.TrazabilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TrazabilidadField, value) != true)) {
                    this.TrazabilidadField = value;
                    this.RaisePropertyChanged("Trazabilidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trazabilidad", Namespace="http://schemas.datacontract.org/2004/07/ServicioMVCEnvios.Models")]
    [System.SerializableAttribute()]
    public partial class Trazabilidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.EstadoPaquete EstadoPaqueteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Guia GuiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdEstadoPaqueteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdGuiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.EstadoPaquete EstadoPaquete {
            get {
                return this.EstadoPaqueteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoPaqueteField, value) != true)) {
                    this.EstadoPaqueteField = value;
                    this.RaisePropertyChanged("EstadoPaquete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Guia Guia {
            get {
                return this.GuiaField;
            }
            set {
                if ((object.ReferenceEquals(this.GuiaField, value) != true)) {
                    this.GuiaField = value;
                    this.RaisePropertyChanged("Guia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstadoPaquete {
            get {
                return this.IdEstadoPaqueteField;
            }
            set {
                if ((this.IdEstadoPaqueteField.Equals(value) != true)) {
                    this.IdEstadoPaqueteField = value;
                    this.RaisePropertyChanged("IdEstadoPaquete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdGuia {
            get {
                return this.IdGuiaField;
            }
            set {
                if ((this.IdGuiaField.Equals(value) != true)) {
                    this.IdGuiaField = value;
                    this.RaisePropertyChanged("IdGuia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origen {
            get {
                return this.OrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigenField, value) != true)) {
                    this.OrigenField = value;
                    this.RaisePropertyChanged("Origen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guia", Namespace="http://schemas.datacontract.org/2004/07/ServicioMVCEnvios.Models")]
    [System.SerializableAttribute()]
    public partial class Guia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PesoPaqueteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Sede SedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPaqueteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Trazabilidad[] TrazabilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorEnvioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CiudadDestino {
            get {
                return this.CiudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadDestinoField, value) != true)) {
                    this.CiudadDestinoField = value;
                    this.RaisePropertyChanged("CiudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionDestino {
            get {
                return this.DireccionDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionDestinoField, value) != true)) {
                    this.DireccionDestinoField = value;
                    this.RaisePropertyChanged("DireccionDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionOrigen {
            get {
                return this.DireccionOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionOrigenField, value) != true)) {
                    this.DireccionOrigenField = value;
                    this.RaisePropertyChanged("DireccionOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdSede {
            get {
                return this.IdSedeField;
            }
            set {
                if ((this.IdSedeField.Equals(value) != true)) {
                    this.IdSedeField = value;
                    this.RaisePropertyChanged("IdSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PesoPaquete {
            get {
                return this.PesoPaqueteField;
            }
            set {
                if ((this.PesoPaqueteField.Equals(value) != true)) {
                    this.PesoPaqueteField = value;
                    this.RaisePropertyChanged("PesoPaquete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receptor {
            get {
                return this.ReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceptorField, value) != true)) {
                    this.ReceptorField = value;
                    this.RaisePropertyChanged("Receptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Sede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoEmisor {
            get {
                return this.TelefonoEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoEmisorField, value) != true)) {
                    this.TelefonoEmisorField = value;
                    this.RaisePropertyChanged("TelefonoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoReceptor {
            get {
                return this.TelefonoReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoReceptorField, value) != true)) {
                    this.TelefonoReceptorField = value;
                    this.RaisePropertyChanged("TelefonoReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPaquete {
            get {
                return this.TipoPaqueteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPaqueteField, value) != true)) {
                    this.TipoPaqueteField = value;
                    this.RaisePropertyChanged("TipoPaquete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Trazabilidad[] Trazabilidad {
            get {
                return this.TrazabilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TrazabilidadField, value) != true)) {
                    this.TrazabilidadField = value;
                    this.RaisePropertyChanged("Trazabilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorEnvio {
            get {
                return this.ValorEnvioField;
            }
            set {
                if ((this.ValorEnvioField.Equals(value) != true)) {
                    this.ValorEnvioField = value;
                    this.RaisePropertyChanged("ValorEnvio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ServicioMVCEnvios.Models")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Guia[] GuiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Guia[] Guia {
            get {
                return this.GuiaField;
            }
            set {
                if ((object.ReferenceEquals(this.GuiaField, value) != true)) {
                    this.GuiaField = value;
                    this.RaisePropertyChanged("Guia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/ServicioMVCEnvios.Models")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.EstadoSede EstadoSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Guia[] GuiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdEstadoSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.EstadoSede EstadoSede {
            get {
                return this.EstadoSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoSedeField, value) != true)) {
                    this.EstadoSedeField = value;
                    this.RaisePropertyChanged("EstadoSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Guia[] Guia {
            get {
                return this.GuiaField;
            }
            set {
                if ((object.ReferenceEquals(this.GuiaField, value) != true)) {
                    this.GuiaField = value;
                    this.RaisePropertyChanged("Guia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstadoSede {
            get {
                return this.IdEstadoSedeField;
            }
            set {
                if ((this.IdEstadoSedeField.Equals(value) != true)) {
                    this.IdEstadoSedeField = value;
                    this.RaisePropertyChanged("IdEstadoSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoSede", Namespace="http://schemas.datacontract.org/2004/07/ServicioMVCEnvios.Models")]
    [System.SerializableAttribute()]
    public partial class EstadoSede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCEnvios.ServiceEstadoPaquete.Sede[] SedeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCEnvios.ServiceEstadoPaquete.Sede[] Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEstadoPaquete.IServicioEstadoPaquete")]
    public interface IServicioEstadoPaquete {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPaquete/ListarEstadosPaquete", ReplyAction="http://tempuri.org/IServicioEstadoPaquete/ListarEstadosPaqueteResponse")]
        MVCEnvios.ServiceEstadoPaquete.EstadoPaquete[] ListarEstadosPaquete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadoPaquete/ListarEstadosPaquete", ReplyAction="http://tempuri.org/IServicioEstadoPaquete/ListarEstadosPaqueteResponse")]
        System.Threading.Tasks.Task<MVCEnvios.ServiceEstadoPaquete.EstadoPaquete[]> ListarEstadosPaqueteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEstadoPaqueteChannel : MVCEnvios.ServiceEstadoPaquete.IServicioEstadoPaquete, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEstadoPaqueteClient : System.ServiceModel.ClientBase<MVCEnvios.ServiceEstadoPaquete.IServicioEstadoPaquete>, MVCEnvios.ServiceEstadoPaquete.IServicioEstadoPaquete {
        
        public ServicioEstadoPaqueteClient() {
        }
        
        public ServicioEstadoPaqueteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEstadoPaqueteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadoPaqueteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadoPaqueteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCEnvios.ServiceEstadoPaquete.EstadoPaquete[] ListarEstadosPaquete() {
            return base.Channel.ListarEstadosPaquete();
        }
        
        public System.Threading.Tasks.Task<MVCEnvios.ServiceEstadoPaquete.EstadoPaquete[]> ListarEstadosPaqueteAsync() {
            return base.Channel.ListarEstadosPaqueteAsync();
        }
    }
}
